### ISSUE TITLE
Combine with Unlocks mod

### ISSUE THREAD

**Issue by robertkent87** [marekzajac97/BF2-HUD-fix#1]
Any chance of combining this with an unlocks mod like https://www.moddb.com/games/battlefield-2/addons/weapon-unlocks? Currently both this and the unlocks replace bf2.exe so I have to choose between the two.

**Comment by marekzajac97** [comment]
Yes, use a DLL injector or modify the Import Address Table it can be done via a free tool called CFF Explorer. I did this for you:
[BF2_with_unlocks.zip](https://github.com/marekzajac97/BF2-HUD-fix/files/6863891/BF2_with_unlocks.zip)
