### ISSUE TITLE
hoping you can update this with weapon unlocks enabled exe

### ISSUE THREAD

**Issue by BenjiBenji69** [marekzajac97/BF2-HUD-fix#3]
I was just getting familiar with dll injection, and the nature of it is simply that it only runs at processes, and resets everytime, and i have limited knowledge with adding and recompiling the exe to have both fixed hud and also weapon unlocks (for single player and coop)

I hope you can update this with adding that exe also, i have one for example if you need one

**Comment by marekzajac97** [comment]
hey, see https://github.com/marekzajac97/BF2-HUD-fix/issues/1

**Comment by BenjiBenji69** [comment]
Oh my god, im so sorry, i didn't realize i was making two issues at once, i thought i forgot to posted it, i see it now and thank you very much
