### ISSUE TITLE
dll injection

### ISSUE THREAD

**Issue by Mitch037** [marekzajac97/BF2-HUD-fix#5]
Hello @marekzajac97,
would it be possible for you to make the hud fix as dll injection (hooking) instead of modyfing exe? This way the fix would be much more versatile and user-friendly for other mods, not to mention playing multiplayer.
One of examples of such a DLL Injector that I am aware of is [ASI Loader](https://github.com/ThirteenAG/Ultimate-ASI-Loader).

**Comment by marekzajac97** [comment]
> This is how my game looks like in-game. Is it correct? Is the minimap scaled properly? I play at resolution 2560x1440.

Yes, what is wrong with it? it's now perfectly round as it's supposed to be.

> Also, I get kicked from multiplayer servers due to detection of modified files (Menu_server.zip). Any idea if it would be possible to inject the fix without modifying game files?

It is doable but would require much more work to swap the type of hud elements on runtime and make them movable. I wonder whether it would make any difference though, if they can detect that you play with modified archives, they could detect the injected .dll as well

**Comment by marekzajac97** [comment]
> > > This is how my game looks like in-game. Is it correct? Is the minimap scaled properly? I play at resolution 2560x1440.
> > 
> > 
> > Yes, what is wrong with it? it's now perfectly round as it's supposed to be.
> 
> Isn't it a bit too big? I'm just giving my opinion. If on the code side it's all correct then I'm fine with it.

It looks correct.

> 
> > > Also, I get kicked from multiplayer servers due to detection of modified files (Menu_server.zip). Any idea if it would be possible to inject the fix without modifying game files?
> > 
> > 
> > It is doable but would require much more work to swap the type of hud elements on runtime and make them movable. I wonder whether it would make any difference though, if they can detect that you play with modified archives, they could detect the injected .dll as well
> 
> From what I know there's checksum check for files when joining to a multiplayer server. I'm not sure if there is any detection of code injection.

Then try joining a server with the fix injected but no menu_server.zip modified. If it doesn't kick you, post a new issue so I can implement this in my spare time.
