### ISSUE TITLE
BF2:SF – NV & Gas Mask adjustment

### ISSUE THREAD

**Issue by ghost** [marekzajac97/BF2-HUD-fix#8]
I've been wondering if Night Vision googles and Gas Mask, which are available in Special Forces expansion, are properly scaled? I compared both in-game (with and without the fix) and both look the same. Is it correct?
<hr>

vanilla
![screen007](https://github.com/marekzajac97/BF2-HUD-fix/assets/93145383/cef0c4ef-4734-48de-9777-9caa4afce77a)
bf2hudfix
![screen004](https://github.com/marekzajac97/BF2-HUD-fix/assets/93145383/47bc5893-faf6-4d34-96c8-c7b34f1dbc13)
<hr>

vanilla
![screen008](https://github.com/marekzajac97/BF2-HUD-fix/assets/93145383/f74429d5-1faf-4ced-bac0-4d0e621cf9f8)
bf2hudfix
![screen005](https://github.com/marekzajac97/BF2-HUD-fix/assets/93145383/bae10229-8902-497f-9661-d8f9af15e071)

**Comment by marekzajac97** [comment]
first of all, these are not part of the HUD framework of the BF2 engine, they're rendered independently. Even if they were, I couldn't make them look any better. There are only two ways to handle it: stretch the 4:3 image on the whole screen (like it is done now) or keep the ratio correct and add black bars on the sides (which arguably is worse as it reduces the FOV).

**Comment by marekzajac97** [comment]
first of all, these are not part of the HUD framework of the BF2 engine, they're rendered independently. Even if they were, I couldn't make them look any better. There are only two ways to handle it: stretch the 4:3 image on the whole screen (like it is done now) or keep the ratio correct and add black bars on the sides (which arguably is worse as it reduces the FOV).
